// 3.2 Vue+ Node.js + MongoDB (MEVN)/frontend/src/pages/Dashboard.vue
<script setup>
import { ref, onMounted } from "vue";
import { api } from "../api";
import { auth } from "../store/auth";
import { useRouter } from "vue-router";

const router = useRouter();
const message = ref("");

onMounted(async () => {
  try {
    const token = auth.getToken();

    const res = await api.get("/api/protected", {
      headers: { Authorization: `Bearer ${token}` },
    });

    message.value = res.data.message;
  } catch (err) {
    alert("Session expired");
    auth.logout();
    router.push("/login");
  }
});
</script>

<template>
  <div class="dashboard-page">
    <div class="dashboard-card">
      <h2>Dashboard</h2>
      <p>{{ message }}</p>
      <button class="btn" @click="auth.logout(); $router.push('/login')">Logout</button>
    </div>
  </div>
</template>

// 3.1 React + Node.js + MongoDB (MERN)/frontend/src/pages/Dashboard.jsx
import React, { useContext, useEffect, useState } from 'react';
import { AuthContext } from '../context/AuthContext';
import { getJSON } from '../api';
import '../styles/dashboard.css';

export default function Dashboard(){
  const { user, token, logout } = useContext(AuthContext);
  const [protectedData, setProtectedData] = useState('');

  useEffect(() => {
    async function fetchData(){
      const { ok, data } = await getJSON('/api/protected', token);
      if (ok) setProtectedData(data.message);
      else {
        alert('Session expired');
        logout();
      }
    }
    fetchData();
  }, [token]);

  return (
    <div className="dashboard-page">
      <div className="dashboard-card">
        <h2>Welcome, {user?.username}</h2>
        <p>{protectedData}</p>
        <div className="actions">
          <button className="btn" onClick={logout}>Logout</button>
        </div>
      </div>
    </div>
  );
}
