// 3.1 React + Node.js + MongoDB (MERN)/frontend/src/pages/Login.jsx
import React, { useState, useContext } from 'react';
import { postJSON } from '../api';
import { AuthContext } from '../context/AuthContext';
import { useNavigate, Link } from 'react-router-dom';
import '../styles/auth.css';

export default function Login(){
  const [form, setForm] = useState({ identifier:'', password:''});
  const { login } = useContext(AuthContext);
  const nav = useNavigate();

  const submit = async e => {
    e.preventDefault();
    const { ok, data } = await postJSON('/api/auth/login', form);
    if (ok) {
      login(data.user, data.token);
      nav('/dashboard');
    } else {
      alert(data?.message || 'Login failed');
    }
  };

  return (
    <div className="auth-page">
      <form onSubmit={submit}>
        <h2>Login</h2>
        <input placeholder="username or email" value={form.identifier} onChange={e=>setForm({...form,identifier:e.target.value})}/>
        <input placeholder="password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>
        <button type="submit">Login</button>
        <div className="auth-nav">
          Don't have an account? <Link to="/signup">Sign up</Link>
        </div>
      </form>
    </div>
  );
}

// 3.2 Vue+ Node.js + MongoDB (MEVN)/frontend/src/pages/Login.vue
<script setup>
import { ref } from "vue";
import { api } from "../api";
import { auth } from "../store/auth";
import { useRouter } from "vue-router";

const router = useRouter();

const identifier = ref("");
const password = ref("");

async function login() {
  try {
    const res = await api.post("/api/auth/login", {
      identifier: identifier.value,
      password: password.value,
    });

    auth.login(res.data.user, res.data.token);
    router.push("/dashboard");
  } catch (err) {
    alert(err.response?.data?.message || "Login failed");
  }
}
</script>

<template>
  <div class="auth-page">
    <div class="auth-card">
      <h2>Login</h2>
      <input v-model="identifier" placeholder="username or email" />
      <input v-model="password" placeholder="password" type="password" />
      <button class="btn" @click="login">Login</button>
      <div class="auth-nav">
        Don't have an account? <router-link to="/signup">Sign up</router-link>
      </div>
    </div>
  </div>
  
</template>
