// 3.1 React + Node.js + MongoDB (MERN)/frontend/src/pages/Signup.jsx
import React, { useState, useContext } from 'react';
import { postJSON } from '../api';
import { AuthContext } from '../context/AuthContext';
import { useNavigate, Link } from 'react-router-dom';
import '../styles/auth.css';

export default function Signup(){
  const [form, setForm] = useState({ username:'', email:'', password:''});
  const { login } = useContext(AuthContext);
  const nav = useNavigate();

  const submit = async e => {
    e.preventDefault();
    const { ok, data } = await postJSON('/api/auth/register', form);
    if (ok) {
      login(data.user, data.token);
      nav('/dashboard');
    } else {
      alert(data?.message || 'Signup failed');
    }
  };

  return (
    <div className="auth-page">
      <form onSubmit={submit}>
        <h2>Sign up</h2>
        <input placeholder="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/>
        <input placeholder="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>
        <input placeholder="password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>
        <button type="submit">Sign up</button>
        <div className="auth-nav">
          Already have an account? <Link to="/login">Login</Link>
        </div>
      </form>
    </div>
  );
}

// 3.2 Vue+ Node.js + MongoDB (MEVN)/frontend/src/pages/Signup.vue
<script setup>
import { ref } from "vue";
import { api } from "../api";
import { auth } from "../store/auth";
import { useRouter } from "vue-router";

const router = useRouter();

const username = ref("");
const email = ref("");
const password = ref("");

async function register() {
  try {
    const res = await api.post("/api/auth/register", {
      username: username.value,
      email: email.value,
      password: password.value,
    });

    auth.login(res.data.user, res.data.token);
    router.push("/dashboard");
  } catch (err) {
    alert(err.response?.data?.message || "Signup failed");
  }
}
</script>

<template>
  <div class="auth-page">
    <div class="auth-card">
      <h2>Sign up</h2>
      <input v-model="username" placeholder="username" />
      <input v-model="email" placeholder="email" />
      <input v-model="password" placeholder="password" type="password" />
      <button class="btn" @click="register">Sign up</button>
      <div class="auth-nav">
        Already have an account? <router-link to="/login">Login</router-link>
      </div>
    </div>
  </div>
</template>
